#!/bin/bash

# Check if target directory is provided
if [ -z "$1" ]; then
    echo "Error: Target directory not provided"
    echo "Usage: $0 <target_directory>"
    exit 1
fi

# Get the root directory (where .scripts is located)
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"

# Define paths
SPRITE_DIR="$ROOT_DIR/packages/assets/icons"
TARGET_DIR="$1"
SPRITE_FILE="$SPRITE_DIR/sprites.svg"

# Debug information
echo "Root directory: $ROOT_DIR"
echo "Sprite directory: $SPRITE_DIR"
echo "Target directory: $TARGET_DIR"
echo "Sprite file: $SPRITE_FILE"

# Create directories if they don't exist
mkdir -p "$SPRITE_DIR" "$TARGET_DIR"

# Check if source sprite file exists
if [ ! -f "$SPRITE_FILE" ]; then
    echo "Error: Source sprite file does not exist at $SPRITE_FILE"
    exit 1
fi

# Create target directory if it doesn't exist
mkdir -p "$TARGET_DIR"

# Create temporary file with warning header and source content
TEMP_FILE="$(mktemp)"
cat > "$TEMP_FILE" << 'EOL'
<?xml version="1.0" encoding="UTF-8"?>
<!--
  WARNING: DO NOT EDIT THIS FILE DIRECTLY
  This file is auto-generated from packages/ui-assets/icons/sprites.svg
  Any direct changes to this file will be overwritten.
  To make changes, edit the source file instead.
-->
EOL

# Append the source file content (skipping its XML declaration)
tail -n +2 "$SPRITE_FILE" >> "$TEMP_FILE"

# Copy the combined file to the target
cp -f "$TEMP_FILE" "$TARGET_DIR/sprites.svg"
rm "$TEMP_FILE"

# Verify the copy was successful
if [ ! -f "$TARGET_DIR/sprites.svg" ]; then
    echo "Error: Failed to copy sprite file to $TARGET_DIR"
    exit 1
fi

echo "Successfully copied sprite file to $TARGET_DIR with warning header"
